name: ${PROJECT_SLUG:-automalar}
version: "3.8"

services:
  automalar-main:
    container_name: ${PROJECT_SLUG:-automalar}
    working_dir: ${WORKSPACE_PATH:-/automalar}
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ..:${WORKSPACE_PATH:-/automalar}:cached
      - /var/run/docker.sock:/var/run/docker.sock
    command: sleep infinity
    networks:
      - ${PROJECT_SLUG:-automalar}_dev_network
      - ${WEB_PROJECT_SLUG:-automalar-web}_dev_network


  automalar-web-app:
    extends:
      file: ../automalar-web/.devcontainer/docker-compose.yml
      service: app
    working_dir: ${WORKSPACE_PATH:-/automalar}${WEB_WORKSPACE_PATH:-/automalarweb}
    volumes:
      - ..:${WORKSPACE_PATH:-/automalar}${WEB_WORKSPACE_PATH:-/automalarweb}:cached
    environment:
      - WORKSPACE_PATH=${WORKSPACE_PATH:-/automalar}${WEB_WORKSPACE_PATH:-/automalarweb}
    depends_on:
      automalar_web_db: { condition: service_healthy }
      automalar_web_cognee: { condition: service_started }
    profiles: ["web", "all"]

  automalar_web_db:
    extends:
      file: ../automalar-web/.devcontainer/docker-compose.yml
      service: db
    profiles: ["web", "web-db", "all"]

  automalar_web_cognee:
    extends:
      file: ../automalar-web/.devcontainer/docker-compose.yml
      service: cognee-mcp
    working_dir: ${WORKSPACE_PATH:-/automalar}${WEB_WORKSPACE_PATH:-/automalarweb}
    volumes:
      - ..:${WORKSPACE_PATH:-/automalar}${WEB_WORKSPACE_PATH:-/automalarweb}:cached
    environment:
      - WORKSPACE_PATH=${WORKSPACE_PATH:-/automalar}${WEB_WORKSPACE_PATH:-/automalarweb}
    profiles: ["web", "web-cognee", "all"]

networks:
  dev_network:
    name: ${PROJECT_SLUG:-automalar}_dev_network
    driver: bridge
  web_dev_network:
    name: ${PROJECT_SLUG:-automalar-web}_dev_network
    driver: bridge

volumes:
  node_modules_devcontainer:
  next_cache_devcontainer:
  storybook_cache_devcontainer:
  postgres_data_devcontainer:
  zsh_history_devcontainer:
