name: automalar
version: '3.8'

services:
  automalar-main:
    container_name: automalar-main
    working_dir: ${WORKSPACE_PATH-/automalar}
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ..:${WORKSPACE_PATH-/automalar}:cached
      - /var/run/docker.sock:/var/run/docker.sock
    command: sleep infinity
    networks:
      - ${PROJECT_NAME-automalar}_dev_network


  automalar-web-app:
    extends:
      file: ../automalar-web/.devcontainer/docker-compose.yml
      service: app
    working_dir: ${WORKSPACE_PATH-/automalar}/automalarweb
    volumes:
      - ..:${WORKSPACE_PATH-/automalar}/automalarweb:cached
    environment:
      - WORKSPACE_PATH=${WORKSPACE_PATH-/automalar}/automalarweb
    user: ${WORKSPACE_USER-node}
    depends_on:
      automalar_web_db: { condition: service_healthy }
      automalar_web_cognee: { condition: service_started }
    profiles: ["web", "all"]

  automalar_web_db:
    extends:
      file: ../automalar-web/.devcontainer/docker-compose.yml
      service: db
    container_name: automalar_integrated_postgres
    profiles: ["web", "web-db", "all"]

  automalar_web_cognee:
    extends:
      file: ../automalar-web/.devcontainer/docker-compose.yml
      service: cognee-mcp
    working_dir: ${WORKSPACE_PATH-/automalar}/automalarweb
    volumes:
      - ..:${WORKSPACE_PATH-/automalar}/automalarweb:cached
    profiles: ["web", "web-cognee", "all"]

networks:
  automalar_dev_network:
    name: automalar_dev_network
    driver: bridge

volumes:
  node_modules_devcontainer:
  next_cache_devcontainer:
  storybook_cache_devcontainer:
  postgres_data_devcontainer:
  zsh_history_devcontainer:
